In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [57]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [58]:
cleaned_data = pd.read_csv("/content/cleaned_data (1).csv")

In [59]:
cleaned_data.head()

ListingKey  ListingNumber            ListingCreationDate  CreditGrade  \
0        7176         193129  2007-08-26 19:09:29.263000000            3   
1        7189        1209647  2014-02-27 08:28:07.900000000            3   
2        6643          81716  2007-01-05 15:00:47.090000000            6   
3        6665         658116  2012-10-22 11:02:35.010000000            3   
4        6682         909464  2013-09-14 18:38:39.097000000            3   

   Term  LoanStatus  ClosedDate  BorrowerAPR  BorrowerRate  LenderYield  \
0    36           0        1126      0.16516        0.1580       0.1380   
1    36           0        2792      0.12016        0.0920       0.0820   
2    36           0        1251      0.28269        0.2750       0.2400   
3    36           0        2792      0.12528        0.0974       0.0874   
4    36           0        2792      0.24614        0.2085       0.1985   

   EstimatedEffectiveYield  EstimatedLoss  EstimatedReturn  \
0                  0.16150         0.0724          0.09170   
1                  0.07960         0.0249          0.05470   
2                  0.16150         0.0724          0.09170   
3                  0.08490         0.0249          0.06000   
4                  0.18316         0.0925          0.09066   

   ProsperRating (numeric)  ProsperRating (Alpha)  ProsperScore  \
0                      4.0                      3           6.0   
1                      6.0                      0           7.0   
2                      4.0                      3           6.0   
3                      6.0                      0           9.0   
4                      3.0                      4           4.0   

   ListingCategory (numeric)  BorrowerState  Occupation  EmploymentStatus  \
0                          0              5          35                 7   
1                          2              5          41                 0   
2                          0             10          35                 2   
3                         16             10          50                 0   
4                          2             23          19                 0   

   EmploymentStatusDuration  IsBorrowerHomeowner  CurrentlyInGroup  \
0                       2.0                    1                 1   
1                      44.0                    0                 0   
2                      67.0                    0                 1   
3                     113.0                    1                 0   
4                      44.0                    1                 0   

   DateCreditPulled  CreditScoreRangeLower  CreditScoreRangeUpper  \
0             14321                  640.0                  659.0   
1            111857                  680.0                  699.0   
2              6420                  480.0                  499.0   
3             64698                  800.0                  819.0   
4             85831                  680.0                  699.0   

   CurrentCreditLines  OpenCreditLines  TotalCreditLinespast7years  \
0                 5.0         4.000000                        12.0   
1                14.0        14.000000                        29.0   
2                10.0         9.260164                         3.0   
3                 5.0         5.000000                        29.0   
4                19.0        19.000000                        49.0   

   OpenRevolvingAccounts  OpenRevolvingMonthlyPayment  InquiriesLast6Months  \
0                      1                         24.0                   3.0   
1                     13                        389.0                   3.0   
2                      0                          0.0                   0.0   
3                      7                        115.0                   0.0   
4                      6                        220.0                   1.0   

   TotalInquiries  CurrentDelinquencies  AmountDelinquent  \
0             3.0                   2.0        472.000000   
1 

In [60]:
cleaned_data.LoanStatus.value_counts()

LoanStatus
0    98849
1    15063
Name: count, dtype: int64

In [61]:
cleaned_data.columns

Index(['ListingKey', 'ListingNumber', 'ListingCreationDate', 'CreditGrade',
       'Term', 'LoanStatus', 'ClosedDate', 'BorrowerAPR', 'BorrowerRate',
       'LenderYield', 'EstimatedEffectiveYield', 'EstimatedLoss',
       'EstimatedReturn', 'ProsperRating (numeric)', 'ProsperRating (Alpha)',
       'ProsperScore', 'ListingCategory (numeric)', 'BorrowerState',
       'Occupation', 'EmploymentStatus', 'EmploymentStatusDuration',
       'IsBorrowerHomeowner', 'CurrentlyInGroup', 'DateCreditPulled',
       'CreditScoreRangeLower', 'CreditScoreRangeUpper', 'CurrentCreditLines',
       'OpenCreditLines', 'TotalCreditLinespast7years',
       'OpenRevolvingAccounts', 'OpenRevolvingMonthlyPayment',
       'InquiriesLast6Months', 'TotalInquiries', 'CurrentDelinquencies',
       'AmountDelinquent', 'DelinquenciesLast7Years',
       'PublicRecordsLast10Years', 'PublicRecordsLast12Months',
       'RevolvingCreditBalance', 'BankcardUtilization',
       'AvailableBankcardCredit', 'TotalTrades',
    

In [62]:
cleaned_data.isnull().sum()

ListingKey                             0
ListingNumber                          0
ListingCreationDate                    0
CreditGrade                            0
Term                                   0
LoanStatus                             0
ClosedDate                             0
BorrowerAPR                            0
BorrowerRate                           0
LenderYield                            0
EstimatedEffectiveYield                0
EstimatedLoss                          0
EstimatedReturn                        0
ProsperRating (numeric)                0
ProsperRating (Alpha)                  0
ProsperScore                           0
ListingCategory (numeric)              0
BorrowerState                          0
Occupation                             0
EmploymentStatus                       0
EmploymentStatusDuration               0
IsBorrowerHomeowner                    0
CurrentlyInGroup                       0
DateCreditPulled                       0
CreditScoreRange

In [63]:
x= cleaned_data.drop(columns=['LoanStatus','LoanOriginationDate','ListingCreationDate',"ListingNumber"] ,axis=1)
y= cleaned_data['LoanStatus']

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
sm = SMOTE(sampling_strategy=.40,random_state=42)
X_train_resample, y_train_resample = sm.fit_resample(x, y)

In [ ]:
y_train_resample.value_counts()

LoanStatus
0    98849
1    39539
Name: count, dtype: int64

In [ ]:
y_train_resample.value_counts(normalize=True)

LoanStatus
0    0.714289
1    0.285711
Name: proportion, dtype: float64

In [ ]:
# Orginal Shape of DataSet
print(x.shape)
print(y.shape)
# After Resampling with Somte
print(X_train_resample.shape)
print(y_train_resample.shape)

(113912, 75)
(113912,)
(138388, 75)
(138388,)


In [ ]:
x = X_train_resample
x.head()

ListingKey  CreditGrade  Term  ClosedDate  BorrowerAPR  BorrowerRate  \
0        7176            3    36        1126      0.16516        0.1580   
1        7189            3    36        2792      0.12016        0.0920   
2        6643            6    36        1251      0.28269        0.2750   
3        6665            3    36        2792      0.12528        0.0974   
4        6682            3    36        2792      0.24614        0.2085   

   LenderYield  EstimatedEffectiveYield  EstimatedLoss  EstimatedReturn  \
0       0.1380                  0.16150         0.0724          0.09170   
1       0.0820                  0.07960         0.0249          0.05470   
2       0.2400                  0.16150         0.0724          0.09170   
3       0.0874                  0.08490         0.0249          0.06000   
4       0.1985                  0.18316         0.0925          0.09066   

   ProsperRating (numeric)  ProsperRating (Alpha)  ProsperScore  \
0                      4.0                      3           6.0   
1                      6.0                      0           7.0   
2                      4.0                      3           6.0   
3                      6.0                      0           9.0   
4                      3.0                      4           4.0   

   ListingCategory (numeric)  BorrowerState  Occupation  EmploymentStatus  \
0                          0              5          35                 7   
1                          2              5          41                 0   
2                          0             10          35                 2   
3                         16             10          50                 0   
4                          2             23          19                 0   

   EmploymentStatusDuration  IsBorrowerHomeowner  CurrentlyInGroup  \
0                       2.0                    1                 1   
1                      44.0                    0                 0   
2                      67.0                    0                 1   
3                     113.0                    1                 0   
4                      44.0                    1                 0   

   DateCreditPulled  CreditScoreRangeLower  CreditScoreRangeUpper  \
0             14321                  640.0                  659.0   
1            111857                  680.0                  699.0   
2              6420                  480.0                  499.0   
3             64698                  800.0                  819.0   
4             85831                  680.0                  699.0   

   CurrentCreditLines  OpenCreditLines  TotalCreditLinespast7years  \
0                 5.0         4.000000                        12.0   
1                14.0        14.000000                        29.0   
2                10.0         9.260164                         3.0   
3                 5.0         5.000000                        29.0   
4                19.0        19.000000                        49.0   

   OpenRevolvingAccounts  OpenRevolvingMonthlyPayment  InquiriesLast6Months  \
0                      1                         24.0                   3.0   
1                     13                        389.0                   3.0   
2                      0                          0.0                   0.0   
3                      7                        115.0                   0.0   
4                      6                        220.0                   1.0   

   TotalInquiries  CurrentDelinquencies  AmountDelinquent  \
0             3.0                   2.0        472.000000   
1             5.0                   0.0          0.000000   
2             1.0                   1.0        984.507059   
3             1.0                   4.0      10056.000000   
4             9.0                   0.0          0.000000   

   DelinquenciesLast7Years  PublicRecordsLast10Years  \
0                      4.0                       0.0   
1                      0

In [ ]:
y = y_train_resample
y.head()

0    0
1    0
2    0
3    0
4    0
Name: LoanStatus, dtype: int64

# **MODEL BUILDING**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [ ]:
# Split the data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)


In [ ]:
len(x_train), len(x_test), len(y_train), len(y_test)

(96871, 41517, 96871, 41517)

In [ ]:
# Standardize the data
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)


In [ ]:
# Logistic Regression
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(x_train_scaled, y_train)

# Predictions
y_pred_log_reg = log_reg.predict(x_test_scaled)

# Evaluation
print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_log_reg))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log_reg))
print("Classification Report:\n", classification_report(y_test, y_pred_log_reg))


Logistic Regression
Accuracy: 0.9980008189416384
Confusion Matrix:
 [[29620    73]
 [   10 11814]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     29693
           1       0.99      1.00      1.00     11824

    accuracy                           1.00     41517
   macro avg       1.00      1.00      1.00     41517
weighted avg       1.00      1.00      1.00     41517



In [ ]:
#Logistic Regression
#Accuracy: 0.9987417334815942
#Confusion Matrix:
# [[29623    20]
# [   23  4508]]

In [ ]:
# Naive Bayes
nb = GaussianNB()
nb.fit(x_train_scaled, y_train)

# Predictions
y_pred_nb = nb.predict(x_test_scaled)

# Evaluation
print("Naive Bayes")
print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))
print("Classification Report:\n", classification_report(y_test, y_pred_nb))


Naive Bayes
Accuracy: 0.9415901919695546
Confusion Matrix:
 [[27290  2403]
 [   22 11802]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.92      0.96     29693
           1       0.83      1.00      0.91     11824

    accuracy                           0.94     41517
   macro avg       0.92      0.96      0.93     41517
weighted avg       0.95      0.94      0.94     41517



In [ ]:
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
adaboost_model = AdaBoostClassifier(n_estimators=50, random_state=42)
adaboost_model.fit(x_train, y_train)

AdaBoostClassifier(random_state=42)

In [ ]:
y_pred = adaboost_model.predict(x_test)
adaboost_accuracy = accuracy_score(y_test, y_pred)

print(f"AdaBoost Model Accuracy: {adaboost_accuracy:.2f}")

AdaBoost Model Accuracy: 1.00


In [ ]:
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score
print ("ADABOOST SCORES ---->>>>")
# Confusion Matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)

# F1 Score
f1_score_value = f1_score(y_test, y_pred, average='weighted')
print(f"F1 Score: {f1_score_value:.2f}")

# Precision
precision_value = precision_score(y_test, y_pred, average='weighted')
print(f"Precision: {precision_value:.2f}")

# Recall
recall_value = recall_score(y_test, y_pred, average='weighted')
print(f"Recall: {recall_value:.2f}")

print(f"AdaBoost Model Accuracy: {adaboost_accuracy:.2f}")

ADABOOST SCORES ---->>>>
Confusion Matrix:
 [[29693     0]
 [    0 11824]]
F1 Score: 1.00
Precision: 1.00
Recall: 1.00
AdaBoost Model Accuracy: 1.00


In [ ]:
# Initialize SVM classifier
svm_clf = SVC(kernel='linear', C=1.0, random_state=42)

# Fit the model
svm_clf.fit(x_train, y_train)

# Predict using the SVM model
y_pred_svm = svm_clf.predict(x_test)

# Evaluate the model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f'SVM Model Accuracy: {accuracy_svm:.2f}')



SVM Model Accuracy: 1.00


In [ ]:
y_pred_svm = svm_clf.predict(x_test)
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))

SVM Accuracy: 0.9994219235493894


In [ ]:
y_pred_svm = svm_clf.predict(x_test)
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))

In [ ]:
print ("SVM SCORES ---->>>>")
# Confusion Matrix
confusion_mat = confusion_matrix(y_test, y_pred_svm)
print("Confusion Matrix:\n", confusion_mat)

# F1 Score
f1_score_value = f1_score(y_test, y_pred_svm, average='weighted')
print(f"F1 Score: {f1_score_value:.2f}")

# Precision
precision_value = precision_score(y_test, y_pred_svm, average='weighted')
print(f"Precision: {precision_value:.2f}")

# Recall
recall_value = recall_score(y_test, y_pred_svm, average='weighted')
print(f"Recall: {recall_value:.2f}")

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))

SVM SCORES ---->>>>
Confusion Matrix:
 [[29679    14]
 [   10 11814]]
F1 Score: 1.00
Precision: 1.00
Recall: 1.00
SVM Accuracy: 0.9994219235493894
